matrix:
  include:
    - language: python
      python:
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - flake8
        - coverage run --source=./app -m pytest
      after_success:
        - coveralls
    - language: node_js
      node_js: 
        - "node"
      script: 
        - npm run lint
